server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead_authuser
    username: root
    password: MapoftheSoul7Bangtan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
       show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      jdbc:
        lob.non-contextual-creation: true
