server:
  port: 8088
  servlet:
    context-path: '/ead-enrollment/'
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead_enrollment
    username: root
    password: MapoftheSoul7Bangtan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQLDialect
       jdbc:
        lob:
          non-contextual-creation: true
  
microservices:
  auth-user: http://localhost:8087/ead-authuser/
  course: http://localhost:8082/ead-course/